bash DataTypesAnalysis_Commands/TCGA_COAD/Prognostic__overall_survival/iteration2/tsv__sklearn__random_forest__default.sh
bash DataTypesAnalysis_Commands/TCGA_COAD/Prognostic__overall_survival/iteration2/tsv__sklearn__svm__default.sh
bash DataTypesAnalysis_Commands/TCGA_LUAD/Prognostic__overall_survival/iteration2/tsv__sklearn__random_forest__default.sh
bash DataTypesAnalysis_Commands/TCGA_LUAD/Prognostic__overall_survival/iteration2/tsv__sklearn__svm__default.sh
