#!/bin/bash

currentDir=$(pwd)

dockerCommandsFile=Docker_Commands.sh
startIteration=1
stopIteration=2
delay=1
numJobs=2
memoryGigs=100
swapMemoryGigs=100
hoursMax=1
numCores=1
outFileToCheck=Predictions.tsv
version=496
datatype=Covariate
python3 createDockerCommands.1.py OutputData $startIteration $stopIteration $memoryGigs $swapMemoryGigs $hoursMax $numCores Algorithms.txt Data_To_Process.txt $outFileToCheck $dockerCommandsFile $version $datatype

jobLogFile=Analysis.job.log
rm -f $jobLogFile
parallel --retries 0 --shuf --progress --eta --delay $delay --joblog $jobLogFile -j $numJobs -- < $dockerCommandsFile
