#!/usr/bin/env bash

endpoint=${1:-PFI}
slurm_environment=${2:-False}
number_of_cores=${3:-16}

if [ ! -d "InputData/" ]; then
mkdir InputData/
fi

if [ ! -d "Analysis_Results/" ]; then
mkdir Analysis_Results/
fi

if [ ! -d "Permanent_Results/" ]; then
mkdir Permanent_Results/
fi

docker run --rm --memory 200G --memory-swap 200G \
       -w /DataTypesAnalysis \
       -v "$(pwd)/InputData/":"/DataTypesAnalysis/InputData/" \
       -v "$(pwd)/Analysis_Results/":"/DataTypesAnalysis/Analysis_Results/" \
       -v "$(pwd)/Permanent_Results/":"/DataTypesAnalysis/Permanent_Results/" dta \
       bash run_entire_project.sh $endpoint $slurm_environment $number_of_cores