#!/usr/bin/env bash

endpoints=$1
numJobs=$2

if [ ! -d "InputData/" ]; then
mkdir InputData/
fi

if [ ! -d "Analysis_Results/" ]; then
mkdir Analysis_Results/
fi

if [ ! -d "Permanent_Results/" ]; then
mkdir Permanent_Results/
fi

docker run dta --rm --memory 200G --memory-swap 200G \
       -v "$(pwd)/InputData/":"/DataTypesAnalysis/InputData/" \
       -v "$(pwd)/Analysis_Results/":"/DataTypesAnalysis/Analysis_Results/" \
       -v "$(pwd)/Permanent_Results/":"/DataTypesAnalysis/Permanent_Results/" dta
       docker exec dta mkdir OutputData/
       docker exec dta cd DataTypesAnalysis
       docker exec dta bash run_entire_project.sh $endpoints $numJobs