---
title: "Create graph based on AUROC & CancerType_Algorithm"
author: "Tyler"
date: "5/6/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

This is a test file for graphing
```{r}
x$CancerType_Algorithm <- paste(x$CancerType,x$Algorithm,sep = "_")
```
```{r}
x <- aggregate(AUROC ~ CancerType_Algorithm + CancerType + Algorithm, x, mean)
```
```{r}
library(ggplot2)
#The Color blind friendly palette with black
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

#change fills default color palette
scale_fill_manual(values = cbPalette)

ggplot(data = x) + geom_col(aes(x = Algorithm, y = AUROC, fill = Algorithm)) + ggtitle(y) + theme(axis.text.x = element_text(angle = 56.5, hjust = 1, vjust = 1, size = 12)) + theme(plot.title = element_text(hjust = .5, size = 20)) +theme(plot.margin=unit(c(1,1,1.5,2),"cm")) + facet_wrap(~CancerType, nrow = 2)
```


```{r}
### should read in the file to be graphed
### It doesn't work though... find out why the absolute path doesn't work or another way to do it.
data <- read_tsv("~/PycharmProjects/Piccolo_Summer_Project/DataTypesAnalysis/Files_To_Be_Graphed/Covariate_Alone.tsv")
x$CancerType_Algorithm <- paste(x$CancerType,x$Algorithm,sep = "_")

x <- aggregate(AUROC ~ CancerType_Algorithm + CancerType + Algorithm, x, mean)

library(ggplot2)
#The Color blind friendly palette with black
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

#change fills default color palette
scale_fill_manual(values = cbPalette)

ggplot(data = x) + geom_col(aes(x = Algorithm, y = AUROC, fill = Algorithm)) + ggtitle(y) + theme(axis.text.x = element_text(angle = 56.5, hjust = 1, vjust = 1, size = 12)) + theme(plot.title = element_text(hjust = .5, size = 20)) +theme(plot.margin=unit(c(1,1,1.5,2),"cm")) + facet_wrap(~CancerType, nrow = 2)
```

